 
					<ul>
            
						<li>
							<h2>RF Tags Custom</h2>
              
							<p><a target="new" href="http://www.rftags.co.za/tags/ShowReaders.php">View Readers</a>
              <br><a target="new" href="http://www.rftags.co.za/ss_admin/Knowledgebase/index.php">Knowledgebase</a>
              <br><a target="new" href="http://www.rftags.co.za/ss_admin/Hints/index.php">Documents</a>
              <br><a href="http://www.rftags.co.za/eclfiles/admin/calendar">Calendar</a>
              <br><a href="http://www.rftags.co.za/ss_admin/videos/index.php">Video Downloads</a>
              <br><a href="http://www.rftags.co.za/eclfiles/admin/SerialNumbers">Serial Numbers</a>
              
              </p>
						</li>
            
					</ul>