				<div id="sidebar">
				<h2>Invoices</h2>
				<p><a href="/invoices/index.php">Quick Add</a>
				<!--br>
				<a href="/invoices/multiple.php">Add Multiple</a-->
				<br>
				<a href="/invoices/search.php">Search</a></p>
        
    
				<h2>Reports</h2>
				<p><a href="/Reports/index.php">Reports</a>

        
				<h2>Categories</h2>
				<p><a href="/Categories/index.php">List Categories</a>
				<br>
				<a href="/Categories/edit.php">Add New</a></p>
        
          
				<h2>Suppliers</h2>
				<p><a href="/Suppliers/index.php">List Suppliers</a>
				<br>
				<a href="/Suppliers/edit.php">Add New</a></p>
				
				</div>